openapi: 3.0.3
info:
  title: Post API
  description: |-
    게시판 CRUD API, 회원가입 및 로그인 API 제공
servers:
  - url: http://localhost:3000
tags:
  - name: board
    description: 게시판에 대한 게시글 CRUD API
    externalDocs:
      description: Find out more
      url: http://localhost:3000/board/list
  - name: user
    description: 회원가입 및 로그인, 회원 정보 수정 API
    # externalDocs:
    #   description: Find out more
    #   url: http://localhost:3000/user
  - name: admin
    description: 어드민 계정 API
    # externalDocs:
    #   description: Find out more
    #   url: http://localhost:3000/admin
